name: Release

on:
  workflow_dispatch:
    inputs:
      bump_type:
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  submit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Update Version
        run: |
          bun run ./scripts/version.ts ${{ github.event.inputs.bump_type }}
          echo VERSION="v$(cat package.json | jq -r '.version')" >> "${GITHUB_ENV}"

      - name: Zip Extensions
        run: |
          bun zip
          bun zip:firefox

      - name: Submit to Stores
        run: |
          bun wxt submit \
            --chrome-zip dist/*-chrome.zip \
            --firefox-zip dist/*-firefox.zip --firefox-sources-zip dist/*-sources.zip
        env:
          CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
          CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
          FIREFOX_EXTENSION_ID: ${{ secrets.FIREFOX_EXTENSION_ID }}
          FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
          FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}

      - name: Push tag to GitHub
        run: |
          git push
          git push --tags

      - name: Create Release to GitHub
        run: |
          gh release create "${VERSION}"
          gh release upload "${VERSION}" dist/*.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
